# -*- coding: utf-8 -*-
"""Chatbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tWH1-00JkztFiOvyecyFduF8X8Nwy4Jr
"""

def chatbot(input_text):
    # Convert user input to lowercase for easier matching
    input_text = input_text.lower()

    # rules and corresponding responses
    if "hello" in input_text:
        return "Hello Tsion! How can I assist you today?"
    elif "Can you assist me with my question" in input_text:
        return "Yes, I can assist you and help you with your questions!"
    elif "How can i apply for scholarship" in input_text:
         return "First I would advice you to look for the universty links then "
    elif "goodbye" in input_text:
        return "Goodbye! Have a great day!"
    else:
        return "I'm sorry, I didn't understand that. Can you please rephrase your question?"

while True:
    user_input = input("User: ")
    response = chatbot(user_input)
    print("Chatbot:", response)

!